- name: Install Apache
  hosts: all
  become: true
  
  tasks:
  - name: Install python3
    apt:
      name: python3
      state: present
  - name: Install Apache
    apt:
      name: apache2
      state: present
  
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes
